---
title: "My Growth as a Data Scientist"
format: html
editor: visual
---

I think the greatest growth I went through as a data scientist was through tidying and organizing data. In previous statistics classes, I had trouble working with datasets I had found online for projects. This was because columns had bad names, had incorrect data types, or was formatted in a way that was difficult to work with. This was apparent with most or all datasets I had found online and made working with them in software like JMP to make graphs and regressions impossible. Now that I have taken this class, I know how to pivot, join, and filter data sets. I also learned how to mutate, rename, and change data types of columns. With these skills, I am confident that I can work with more datasets that are not tailor-made by professors or by people who have experience making tidy data sets. One example of this is when I pivoted the avocado_clean dataset wider so that I could make plots of the differences in sales of conventional vs organic avocados. 