---
title: "The Power of Efficiency"
format: html
editor: visual
---

In general, efficiency means being able to do the most amount of work while expending the least amount of energy or having little to no wasted energy. In statistical computing, efficiency means not repeating one's self in terms of code. For example, if I needed to add the values of a 100 integer vector together, instead of repeatedly adding values one by one, I could use a for loop to do what was done in 100 lines in 3 or 4. Additionally, If I had a chunk of code that would be used multiple times throughout a file, I could put it in a function and call the function instead. Or, if I needed to apply a function to a vector of values, rather than calling that function for every value in the vector, I could use a map function to accomplish it, reducing the number of lines in my code and reducing repetition. Efficiency allows us to write fewer lines of code, makes our code easier to read and edit, and makes it so there is less room for mistakes in our code. I encountered efficiency in the '12 days of Christmas' lab. Rather than calling a function to transform each of the 12 lines of the dataset into a line of the song, I used the map function to accomplish this in 4 lines. One aha moment I had was learning that instead of calling mutate multiple times to mutate multiple columns, I could call them all in one mutate call, such as in PA5 question 1.

------------------------------------------------------------------------
